import type { Artist, Artwork } from "@/types";

export const initialArtists: Artist[] = [
  {
    id: "leonardo-da-vinci",
    nome: "Leonardo da Vinci",
    biografia: `Leonardo di ser Piero da Vinci (1452–1519) foi o arquétipo do homem renascentista. Pintor, escultor, arquiteto, engenheiro, anatomista e inventor. Nasceu perto de Vinci, na República de Florença. Sua obra une observação científica rigorosa com sensibilidade humana profunda. A *Mona Lisa* permanece o retrato mais enigmático da história da arte.`,
    nacionalidade: "Italiano",
    periodoAtividade: "1460–1519",
    movimentoPrincipal: "Renascimento",
    urlFotoArtista: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Francesco_Melzi_-_Portrait_of_Leonardo.jpg/440px-Francesco_Melzi_-_Portrait_of_Leonardo.jpg",
    musicaEpoca: "Música renascentista: motetos de Josquin des Prez, frottole italianas. Instrumentos: alaúde, viola da gamba, flauta doce.",
    modaEpoca: "Homens: gibão, calções, capa. Mulheres: vestidos com mangas destacáveis, toucas. Tecidos ricos, veludo e seda. Cores profundas.",
    contextoHistorico: "Itália do Quattrocento e Cinquecento. Florença sob os Médici. Milão sob os Sforza. O humanismo coloca o homem no centro.",
  },
  {
    id: "claude-monet",
    nome: "Claude Monet",
    biografia: `Oscar-Claude Monet (1840–1926) é o pai do Impressionismo. Nascido em Paris e criado em Le Havre, dedicou a vida a capturar a luz e a atmosfera em constante mudança. *Impressão, nascer do sol* (1872) deu nome ao movimento. Seus últimos anos foram consumidos pelos *Nenúfares* de Giverny.`,
    nacionalidade: "Francês",
    periodoAtividade: "1860–1926",
    movimentoPrincipal: "Impressionismo",
    urlFotoArtista: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Claude_Monet_1899_Nadar_crop.jpg/440px-Claude_Monet_1899_Nadar_crop.jpg",
    musicaEpoca: "Impressionismo musical: Debussy, Ravel. Atmosferas fluidas, harmonia modal, orquestração colorida.",
    modaEpoca: "Belle Époque. Mulheres: espartilho, anquinhas, chapéus elaborados. Homens: casaca, cartola. Cores claras e tecidos leves no verão.",
    contextoHistorico: "França da Terceira República. Revolução industrial, fotografia emergente, rejeição do Salão oficial.",
  },
  {
    id: "vincent-van-gogh",
    nome: "Vincent van Gogh",
    biografia: `Vincent Willem van Gogh (1853–1890) transformou o sofrimento em cor e movimento. Holandês de nascimento, passou seus anos mais produtivos no sul da França. *A Noite Estrelada* (1889) foi pintada no asilo de Saint-Rémy. Vendeu apenas uma pintura em vida. Hoje é um dos artistas mais amados do planeta.`,
    nacionalidade: "Holandês",
    periodoAtividade: "1880–1890",
    movimentoPrincipal: "Pós-Impressionismo",
    urlFotoArtista: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/440px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg",
    musicaEpoca: "Wagner ainda ecoava. Na França: Chabrier, early Debussy. Van Gogh amava a música e frequentemente comparava pintura a música.",
    modaEpoca: "Homens de trabalho: calças largas, camisas simples, chapéu de palha. Camponeses e artistas boêmios rejeitavam o formalismo burguês.",
    contextoHistorico: "Europa fin-de-siècle. Industrialização, miséria rural, nascimento da psiquiatria moderna.",
  },
  {
    id: "pablo-picasso",
    nome: "Pablo Picasso",
    biografia: `Pablo Ruiz Picasso (1881–1973) reinventou a arte várias vezes. Espanhol de Málaga, radicado em Paris. Criou o Cubismo com Braque. *Guernica* (1937) é o grito mais poderoso contra a guerra já pintado. Produziu mais de 20 mil obras.`,
    nacionalidade: "Espanhol",
    periodoAtividade: "1890–1973",
    movimentoPrincipal: "Cubismo",
    urlFotoArtista: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Pablo_picasso_1.jpg/440px-Pablo_picasso_1.jpg",
    musicaEpoca: "Jazz, Stravinsky, Satie. Paris dos anos 20 e 30 fervilhava de experimentação sonora.",
    modaEpoca: "Anos 30: silhueta alongada, chapéus cloche, trajes masculinos sobrios. Guerra e austeridade depois.",
    contextoHistorico: "Guerra Civil Espanhola, ascensão do fascismo, Segunda Guerra Mundial. Paris como capital da vanguarda.",
  },
  {
    id: "salvador-dali",
    nome: "Salvador Dalí",
    biografia: `Salvador Domingo Felipe Jacinto Dalí i Domènech (1904–1989) foi o showman do Surrealismo. Catalão de Figueres. *A Persistência da Memória* (1931) com seus relógios moles tornou-se ícone mundial. Misturou paranoico-crítico, ciência e teatro pessoal.`,
    nacionalidade: "Espanhol",
    periodoAtividade: "1920–1989",
    movimentoPrincipal: "Surrealismo",
    urlFotoArtista: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Salvador_Dal%C3%AD_1939.jpg/440px-Salvador_Dal%C3%AD_1939.jpg",
    musicaEpoca: "Jazz, música concreta, e a própria obsessão de Dalí por Wagner e pela ópera.",
    modaEpoca: "Surrealismo na moda: Schiaparelli colaborou com Dalí. Chapéus-sapato, vestidos com gavetas, extravagância deliberada.",
    contextoHistorico: "Entre-guerras. Freud, sonho, inconsciente. Guerra Civil Espanhola e exílio.",
  },
  {
    id: "tarsila-do-amaral",
    nome: "Tarsila do Amaral",
    biografia: `Tarsila do Amaral (1886–1973) é a maior pintora modernista brasileira. Paulista. *Abaporu* (1928) inspirou o Movimento Antropofágico de Oswald de Andrade. Misturou cubismo europeu com cores e temas tropicais. Ícone da identidade cultural brasileira.`,
    nacionalidade: "Brasileira",
    periodoAtividade: "1910–1973",
    movimentoPrincipal: "Arte Moderna (Brasil)",
    urlFotoArtista: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Tarsila_do_Amaral_no_Tarsila.jpg/440px-Tarsila_do_Amaral_no_Tarsila.jpg",
    musicaEpoca: "Samba, maxixe, chorinho. Villa-Lobos fundia modernismo e folclore brasileiro.",
    modaEpoca: "Anos 20 brasileiros: influência da moda parisiense misturada ao clima tropical. Cabelos curtos, vestidos soltos.",
    contextoHistorico: "Semana de Arte Moderna de 1922. Busca de uma identidade brasileira moderna e antropofágica.",
  },
  {
    id: "yayoi-kusama",
    nome: "Yayoi Kusama",
    biografia: `Yayoi Kusama (nascida em 1929) é a rainha das bolinhas e das Infinity Rooms. Japonesa de Matsumoto. Desde os anos 60 cria instalações imersivas que dissolvem o eu no infinito. Vive voluntariamente em uma instituição psiquiátrica em Tóquio e continua produzindo com intensidade única.`,
    nacionalidade: "Japonesa",
    periodoAtividade: "1950–presente",
    movimentoPrincipal: "Arte Contemporânea",
    urlFotoArtista: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Yayoi_Kusama.jpg/440px-Yayoi_Kusama.jpg",
    musicaEpoca: "Minimalismo, música eletrônica, ambient. A repetição de Kusama ecoa padrões sonoros hipnóticos.",
    modaEpoca: "Anos 60: mod, futurismo, estampas psicodélicas. Kusama criou sua própria linha de moda e happenings nus.",
    contextoHistorico: "Pós-guerra no Japão, Nova York dos anos 60, arte feminista e arte como terapia.",
  },
];

export const initialArtworks: Artwork[] = [
  {
    id: "mona-lisa",
    titulo: "Mona Lisa",
    urlDaImagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    poemaGerado: "",
    descricaoAnalitica: "Retrato de Lisa Gherardini. Técnica de sfumato. O sorriso enigmático e o olhar que segue o espectador tornaram esta a pintura mais famosa do mundo.",
    anoDeCriacao: 1503,
    dimensoes: "77 cm × 53 cm",
    status: "dominio_publico",
    preco: 0,
    dataDeUpload: new Date().toISOString(),
    artistaRef: "leonardo-da-vinci",
  },
  {
    id: "noite-estrelada",
    titulo: "A Noite Estrelada",
    urlDaImagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/800px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    poemaGerado: "",
    descricaoAnalitica: "Céu noturno em movimento turbulento sobre Saint-Rémy. A cipreste sobe como chama negra. Uma das obras mais reproduzidas da história.",
    anoDeCriacao: 1889,
    dimensoes: "73.7 cm × 92.1 cm",
    status: "dominio_publico",
    preco: 0,
    dataDeUpload: new Date().toISOString(),
    artistaRef: "vincent-van-gogh",
  },
  {
    id: "impressao-nascer",
    titulo: "Impressão, nascer do sol",
    urlDaImagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/800px-Monet_-_Impression%2C_Sunrise.jpg",
    poemaGerado: "",
    descricaoAnalitica: "O quadro que batizou o Impressionismo. Porto de Le Havre ao amanhecer. Luz e atmosfera acima do detalhe.",
    anoDeCriacao: 1872,
    dimensoes: "48 cm × 63 cm",
    status: "dominio_publico",
    preco: 0,
    dataDeUpload: new Date().toISOString(),
    artistaRef: "claude-monet",
  },
  {
    id: "abaporu",
    titulo: "Abaporu",
    urlDaImagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Tarsila_do_Amaral_-_Abaporu.jpg/600px-Tarsila_do_Amaral_-_Abaporu.jpg",
    poemaGerado: "",
    descricaoAnalitica: "Figura com pé e mão enormes sentada sob um sol tropical. Inspirou o Manifesto Antropófago. Símbolo do modernismo brasileiro.",
    anoDeCriacao: 1928,
    dimensoes: "85 cm × 73 cm",
    status: "dominio_publico",
    preco: 0,
    dataDeUpload: new Date().toISOString(),
    artistaRef: "tarsila-do-amaral",
  },
  {
    id: "persistencia-memoria",
    titulo: "A Persistência da Memória",
    urlDaImagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/The_Persistence_of_Memory.jpg/800px-The_Persistence_of_Memory.jpg",
    poemaGerado: "",
    descricaoAnalitica: "Relógios moles derretendo numa paisagem onírica. Tempo e memória se dissolvem. Ícone do Surrealismo.",
    anoDeCriacao: 1931,
    dimensoes: "24 cm × 33 cm",
    status: "dominio_publico",
    preco: 0,
    dataDeUpload: new Date().toISOString(),
    artistaRef: "salvador-dali",
  },
  {
    id: "guernica",
    titulo: "Guernica",
    urlDaImagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Mural_del_Gernika.jpg/800px-Mural_del_Gernika.jpg",
    poemaGerado: "",
    descricaoAnalitica: "Resposta ao bombardeio de Guernica. Preto, branco e cinza. Grito coletivo contra a barbárie da guerra.",
    anoDeCriacao: 1937,
    dimensoes: "349 cm × 776 cm",
    status: "dominio_publico",
    preco: 0,
    dataDeUpload: new Date().toISOString(),
    artistaRef: "pablo-picasso",
  },
  {
    id: "infinity-mirror",
    titulo: "Infinity Mirror Room",
    urlDaImagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Yayoi_Kusama_Infinity_Mirrored_Room.jpg/800px-Yayoi_Kusama_Infinity_Mirrored_Room.jpg",
    poemaGerado: "",
    descricaoAnalitica: "Instalação imersiva de espelhos e luzes que cria a ilusão de espaço infinito. O eu se dissolve na repetição. Experiência contemporânea por excelência.",
    anoDeCriacao: 1965,
    dimensoes: "variável (instalação)",
    status: "dominio_publico",
    preco: 0,
    dataDeUpload: new Date().toISOString(),
    artistaRef: "yayoi-kusama",
  },
];
